name: Docker Image CI

on:
   workflow_dispatch:    
#  push:
#    branches: [ "main" ]

jobs:

    build-overleaf-arm:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Build and push Overleaf ARM base
          uses: docker/build-push-action@v6
          with:
            context: .
            file: server-ce/Dockerfile-base
            platforms: linux/amd64
            push: true
            tags: |
              ghcr.io/${{ github.repository_owner }}/overleaf-arm-base:latest
            cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/overleaf-amd-base:latest
            cache-to: type=inline
    
        - name: Build and push Overleaf ARM
          uses: docker/build-push-action@v6
          with:
            context: .
            file: server-ce/Dockerfile
            platforms: linux/amd64
            push: true
            tags: |
              ghcr.io/${{ github.repository_owner }}/overleaf-arm:latest
            cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/overleaf-amd:latest
            cache-to: type=inline